In [39]:
from up_map import Map

ModuleNotFoundError: No module named 'up_map'

In [18]:
import random


In [30]:
a = np.array([-4, 3, 4, 2, 1])

b = a-min(a)
print(b)
c = sum(b)
print(c)
d = b/c
print(d)

k =np.random.choice(
  range(len(a)), 
  2,
  p=d
)

[0 7 8 6 5]
26
[0.         0.26923077 0.30769231 0.23076923 0.19230769]


In [32]:
k

array([3, 2])

In [11]:
a = np.asarray(a)
a

array([4, 3, 4, 2, 1])

In [16]:
value= np.array([0,0,0,0,5])

In [17]:
np.dot(value,a)

5

In [14]:
b = np.zeros((5,5))
for i in range(5):
    b[a[i],i] = value[i]
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5.],
       [0., 0., 0., 4., 0.],
       [0., 2., 0., 0., 0.],
       [1., 0., 3., 0., 0.]])

In [35]:
a

array([-4,  3,  4,  2,  1])

In [37]:
a

array([-4,  3,  4,  2,  1])