In [1]:
from up_map import Map


In [2]:
import math
import numpy as np
import random
import timeit

In [3]:
class hill_climbing(Map):
    """
    input: Map class
    output:
    """
    def __init__(self,filename):
        Map.__init__(self,filename)

        self.get_map()
        self.current = self.initial_map()
        self.current_score = self.score(self.current)
        self.max_score = self.score(self.current) 
        
        self.restart = 0
        
        self.neighbour = None
        self.during_time =None
        
        self.T = 2
        
    def move_zone(self, position, row, column, type):
        value_original = self.map_board[row,column]
        value = self.current[row,column]
        if value_original != 10 and value != 12 and value != 13 and value != 14:
            self.neighbour = self.current.copy()
            self.neighbour[position[0],position[1]] = 0
            self.neighbour[row,column] = type
            return True
        else:
            return False
        
    def add_zone(self,row,column,type):
        value_original = self.map_board[row,column]
        value = self.current[row,column]
        if value_original != 10 and value != 12 and value != 13 and value != 14:
            self.neighbour = self.current.copy()
            self.neighbour[row,column] = type
            return True
        else:
            return False
            
    def remove_zone(self,position):
        
        self.neighbour = self.current.copy()
        self.neighbour[position[0],position[1]] = 0

        
    def climb(self):
        x_position = np.asarray(np.where(self.map_board == 10)).T
        s_position = np.asarray(np.where(self.map_board == 11)).T
        
        start = timeit.default_timer()
        while self.T > 1:
            neighbours = []
            i_position = np.asarray(np.where(self.current == 12)).T
            c_position = np.asarray(np.where(self.current == 13)).T
            r_position = np.asarray(np.where(self.current == 14)).T
            for row in range(self.row):
                for column in range(self.column):
    #                 industry
                    if len(i_position)>0:
                        for i in i_position:
                            if self.move_zone(i,row,column,12):                     
                                neighbours.append(self.neighbour)

                    if len(i_position) < self.industrial and self.add_zone(row,column,12):
                        self.add_zone(row,column,12)                    
                        neighbours.append(self.neighbour)

    #                 commercial 
                    if len(c_position)>0:
                        for i in c_position:
                            if self.move_zone(i,row,column,13):                    
                                neighbours.append(self.neighbour)


                    if len(c_position) < self.commercial and self.add_zone(row,column,13):
                        self.add_zone(row,column,13)
                        neighbours.append(self.neighbour)

    #                     residential
                    for i in r_position:
                        if self.move_zone(i,row,column,14):
                            neighbours.append(self.neighbour)

                    if len(r_position) < self.residential and self.add_zone(row,column,14):
                        self.add_zone(row,column,14)                 
                        neighbours.append(self.neighbour)
                        
            for i in i_position:
                self.remove_zone(i)                      
                neighbours.append(self.neighbour)
            for i in c_position:
                self.remove_zone(i)                      
                neighbours.append(self.neighbour)
            for i in r_position:
                self.remove_zone(i)                      
                neighbours.append(self.neighbour)
                
            if neighbours:                      
                neighbour = max(neighbours, key=lambda state: self.score(state))
#                 print(neighbour)

                if self.score(neighbour) > self.current_score:
                    self.current = neighbour
                    self.current_score = self.score(neighbour)
                else:
                    neighbour= random.choice(neighbours)
                    if math.exp((self.score(neighbour) - self.current_score)/self.T)>random.uniform(0.0, 1.0):
                        self.current = neighbour
                        self.current_score = self.score(neighbour)
                        self.T = self.T * 10/11
#                         T = T* k/(k+1)
            if not neighbours:
                self.current = self.initial_map()
                self.restart += 1
                break
                
            end = timeit.default_timer()
            if (end - start) > 10:
                break
    
            
#             print(self.current)
#             print(self.current_score)
        self.during_time = end - start   
           

In [4]:
hc = hill_climbing('urban 1.txt')
hc.climb()

(11, 0.9330147604194668, array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0., 13.,  0., 14.]]), 0.15325556899915682, 0)

In [5]:
hc.map_board

array([[10,  1,  2,  4],
       [ 3,  4, 11,  3],
       [ 6,  0,  2,  3]])

In [ ]:
"""
The score for this map
At what time that score was first achieved.
The map, with the various industrial, commercial, and residential sites marked.
"""

In [172]:
neighbours

[array([[ 0., 12.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0., 12.,  0.],
        [ 0.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0., 12.],
        [ 0.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [12.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0., 12.,  0.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0., 12.,  0.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 12.],
        [14.,  0.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [14., 12.,  0.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [14.,  0., 12.,  0.]]), array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [14.,  0.,  0.,  0.]])]

In [214]:
150
0.9575681974766543
array([[ 0., 14., 14., 13.],
        [13., 13.,  0., 14.],
        [ 0., 13., 14., 14.]])

In [205]:
industrial_positions = np.asarray(np.where(map == 12)).T
industrial_positions

array([[1, 2]])

In [184]:
hc.scenic_positions
# hc.toxic_positions

[]

In [ ]:
score = 0
for i in industrial_positions:
    if hc.map_board[i[0], i[1]] == 11:
        score += 1
        scenic_positions.remove([i[0], i[1]])
    else:
        score += self.map_board[i[0], i[1]] + 2

In [196]:
industrial_positions

array([[1, 2]])

In [203]:
industrial_positions[0]

array([1, 2])

In [212]:
for i in industrial_positions:
    print(i[0])
    print(i[0],i[1])
    row = i[0]
    column = i[1]
    list1=[[1,2]]
    list1.remove([i[0],i[1]])


1
1 2


In [4]:
hc = hill_climbing('urban 1.txt')

In [5]:
hc.climb()

(150, 0.9575681974766543, array([[ 0., 14., 14., 13.],
        [13., 13.,  0., 14.],
        [ 0., 13., 14., 14.]]))

In [240]:
print(hc.current)
print(hc.current_score)
print(hc.max_score)
print(hc.scenic_positions)

[[ 0.  0.  0.  0.]
 [14.  0.  0.  0.]
 [ 0.  0.  0. 13.]]
0
0
[[1, 2]]


In [234]:
map = np.array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0., 12.,  0.],
        [14.,  0.,  0.,  0.]])

In [237]:
import copy

In [241]:
scenic_positions = copy.deepcopy(hc.scenic_positions)

In [242]:
for i in np.asarray(np.where(map == 12)).T:
    if hc.map_board[i[0], i[1]] == 11:
        scenic_positions.remove([i[0], i[1]])

In [243]:
hc.scenic_positions

[[1, 2]]

In [6]:
# hc.score(map)

In [55]:
# current_score,T,current = hc.climb()

In [44]:
position = []

In [46]:
if position== True:
    print(True)
else:
    print(2)

2


In [216]:
map = Map('urban 1.txt')
map.get_map()
initial = map.initial_map()
initial

array([[ 0.,  0.,  0.,  0.],
       [ 0., 14.,  0., 13.],
       [ 0.,  0.,  0.,  0.]])

In [217]:
map.scenic_positions

[[1, 2]]

In [4]:
hill_climbing('urban 1.txt').initial

array([[ 0.,  0., 13.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
math.exp(-5/2)

0.0820849986238988

In [9]:
random.uniform(0.0, 1.0)

0.5522703314978357