In [1]:
from NQueens import Queen
import timeit
import numpy as np


In [16]:
class a_star(Queen):
    def __init__(self,filename,heuristic):
        Queen.__init__(self,filename)
        self.input_board()

        self.heuristic = heuristic
        self.frontier = []
        self.come_from = {}
        self.cost_so_far = {}

        self.start_time = timeit.default_timer()
        self.during_time = 0

        self.result = None


    def state_to_tuple(self,state):
        return tuple(np.nonzero(state.T)[1])


    def a_star(self):

        start = self.state_to_tuple(self.start_state)
        self.frontier.append((0, self.start_state))
        self.come_from[start] = None
        self.cost_so_far[start] = 0


        if self.heuristic == 'H1':
            while self.frontier:
                #         sorted(graded, key=lambda x: x[0])
                self.frontier.sort(key=lambda x: x[0], reverse=True)
                current = self.frontier.pop()

                if self.heuristic_1(current[-1]) == 0:
                    self.result = current[-1]
                    break
                for next in self.near_state(current[-1]):
                    new_cost = self.cost_so_far[self.state_to_tuple(current[-1])] + self.compute_cost(current[-1], next)

                    if self.state_to_tuple(next) not in self.cost_so_far:
                        self.cost_so_far[self.state_to_tuple(next)] = new_cost

                        priority = new_cost + self.heuristic_1(next)
                        self.frontier.append((priority, next))

                        self.come_from[self.state_to_tuple(next)] = self.state_to_tuple(current[-1])

                end = timeit.default_timer()

                if (end - self.start_time) > 10:
                    break


In [17]:
filename = 'heavy queens board.csv'
astar = a_star(filename,'H1')
astar.a_star()
print('Start state:')
print(astar.start_state)

Start state:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 4. 0.]
 [0. 3. 0. 0. 0.]
 [9. 0. 1. 0. 0.]]


In [18]:
len(astar.cost_so_far)

1096

In [20]:
result = astar.result
result

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 2.],
       [0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0.],
       [9., 0., 0., 0., 0.]])

In [5]:
print('Final state')
print(astar.result)

Final state
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 2.]
 [0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0.]
 [9. 0. 0. 0. 0.]]


In [21]:
1139**(1/4)

5.809395326655986

In [22]:
result = [4, 2, 5, 3, 1, 39]

In [24]:
result[-1]

39

In [136]:
from board_hillclimbing import Queen
import timeit
import random
import queue
import numpy as np

In [160]:
filename = 'heavy queens board.csv'
q = Queen()
frontier = queue.PriorityQueue()
state = q.input_board(filename)
neighbours= q.near_state(state)

In [164]:
def state_to_tuple(state):
    return tuple(np.nonzero(state.T)[1])


def a_star(q, filename):
    state = q.input_board(filename)
    start = state_to_tuple(state)

    frontier = queue.PriorityQueue()
    frontier.put((0, state))

    come_from = {}
    cost_so_far = {}
    come_from[start] = None
    cost_so_far[start] = 0    

    while not frontier.empty():
        current = frontier.get()

        if q.heuristic_1(current[-1]) == 0:
            result = current[-1]
            break
        for next in q.near_state(current[-1]):
            new_cost = cost_so_far[state_to_tuple(current[-1])] + q.cost(current[-1], next)
            
            if state_to_tuple(next) not in cost_so_far or new_cost < cost_so_far[state_to_tuple(next)]:
                cost_so_far[state_to_tuple(next)] = new_cost

                priority = new_cost + q.heuristic_1(next)
                print(frontier.queue)
                frontier.put((priority, next))
                
#                 frontier.put((new_cost, next))
                come_from[state_to_tuple(next)] = state_to_tuple(current[-1])
                
    node_expanded = len(cost_so_far)
    return result, node_expanded

In [166]:
filename = 'heavy queens board.csv'
q = Queen()
# a_star(q, filename)

In [185]:
def state_to_tuple(state):
    return tuple(np.nonzero(state.T)[1])


def a_star(q, filename):
    state = q.input_board(filename)
    start = state_to_tuple(state)
    
    frontier = []
    frontier.append((0, state))

    come_from = {}
    cost_so_far = {}
    come_from[start] = None
    cost_so_far[start] = 0    
    result = None
    start = timeit.default_timer()
    i= 0
    while frontier:
#         sorted(graded, key=lambda x: x[0])
        frontier.sort(key=lambda x:x[0],reverse=True)
        current = frontier.pop()

        if q.heuristic_1(current[-1]) == 0:
            result = current[-1]
            break
        for next in q.near_state(current[-1]):
            new_cost = cost_so_far[state_to_tuple(current[-1])] + q.cost(current[-1], next)+q.heuristic_1(next)
            
            if state_to_tuple(next) not in cost_so_far:
                cost_so_far[state_to_tuple(next)] = new_cost
                
                priority = new_cost + q.heuristic_1(next)
                frontier.append((new_cost, next))
               
                come_from[state_to_tuple(next)] = state_to_tuple(current[-1])
        end = timeit.default_timer()
        i=i+1
        print(i)
        if (end - start) > 10:
            break
    
    end = timeit.default_timer()
    during_time = end - start                
    node_expanded = len(cost_so_far)
    return state, node_expanded, during_time, result

In [186]:
#  or new_cost < cost_so_far[state_to_tuple(next)]
filename = 'heavy queens board.csv'
q = Queen()
a_star(q,filename)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212


(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 2.],
        [0., 0., 0., 4., 0.],
        [0., 3., 0., 0., 0.],
        [9., 0., 1., 0., 0.]]),
 1432,
 0.4644432449986198,
 array([[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 2.],
        [0., 3., 0., 0., 0.],
        [0., 0., 0., 4., 0.],
        [9., 0., 0., 0., 0.]]),
 {(4, 3, 4, 2, 1): 0,
  (0, 3, 4, 2, 1): 325.0,
  (1, 3, 4, 2, 1): 244.0,
  (2, 3, 4, 2, 1): 163.0,
  (3, 3, 4, 2, 1): 82.0,
  (4, 0, 4, 2, 1): 28.0,
  (4, 1, 4, 2, 1): 19.0,
  (4, 2, 4, 2, 1): 10.0,
  (4, 4, 4, 2, 1): 10.0,
  (4, 3, 0, 2, 1): 8.0,
  (4, 3, 1, 2, 1): 4.0,
  (4, 3, 2, 2, 1): 3.0,
  (4, 3, 3, 2, 1): 2.0,
  (4, 3, 4, 0, 1): 33.0,
  (4, 3, 4, 1, 1): 17.0,
  (4, 3, 4, 3, 1): 17.0,
  (4, 3, 4, 4, 1): 33.0,
  (4, 3, 4, 2, 0): 5.0,
  (4, 3, 4, 2, 2): 5.0,
  (4, 3, 4, 2, 3): 9.0,
  (4, 3, 4, 2, 4): 13.0,
  (0, 3, 3, 2, 1): 327.0,
  (1, 3, 3, 2, 1): 246.0,
  (2, 3, 3, 2, 1): 165.0,
  (3, 3, 3, 2, 1): 84.0,
  (4, 0, 3, 2, 1): 30.0,
  (4, 1, 3, 2, 1): 21.

In [43]:
state = q.input_board(filename)
start = state_to_tuple(state)

frontier = queue.PriorityQueue()
frontier.put((0, state))

come_from = {}
cost_so_far = {}
come_from[tuple(start)] = None
cost_so_far[tuple(start)] = 0 

In [35]:
current = frontier.get()

In [38]:
type(current[-1])

numpy.ndarray

In [39]:
type(current[1])

numpy.ndarray

In [45]:
while not frontier.empty():
    current = frontier.get()
    print(current)
    if q.heuristic_1(current[-1]) == 0:
        result = current[-1]
        break
    for next in q.near_state(current[-1]):
        new_cost = cost_so_far[state_to_tuple(current[-1])] + q.cost(current[-1], next)
        if state_to_tuple(next) not in cost_so_far or new_cost < cost_so_far[state_to_tuple(next)]:
            cost_so_far[state_to_tuple(next)] = new_cost
            priority = new_cost + q.heuristic_1(next)
            frontier.put((priority, next)
            come_from[state_to_tuple(next)] = state_to_tuple(current[-1])
    

SyntaxError: invalid syntax (<ipython-input-45-56e63398cd2a>, line 13)