In [2]:
import numpy as np
import copy

In [3]:
class queen_astar():

    def input_board(self, filename):
        """
        input: filename
        output: a array like matrix
        ex:
        array([[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 2.],
           [0., 0., 0., 4., 0.],
           [0., 3., 0., 0., 0.],
           [9., 0., 1., 0., 0.]])
        """
        state = np.genfromtxt(filename, delimiter=',')
        state[np.isnan(state)] = 0
        return state
    
    def board_value(self,state):
        board = np.nonzero(state.T)[1]
        value = []
        for i in range(len(board)):
            value.append(state[board[i],i]**2)
        return value
    
    
    def heuristic_1(self, state):
        """
        H1: The lightest Queen across all pairs of Queens attacking each other.
        ex: min(3,9, 9,1, 3,1, 4,2) = 1**1
        input: state
        ex: 
        array([[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 2.],
           [0., 0., 0., 4., 0.],
           [0., 3., 0., 0., 0.],
           [9., 0., 1., 0., 0.]])
        output: H1 score
        """
        board = np.nonzero(state.T)[1]
        min_attact = []
        for i in range(len(board)):
            for j in range(i+1,len(board)):
                # check same rows attack
                if board[i] == board[j]:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
                # check diagonally attack
                offset = j-i
                if board[i] == board[j] - offset or board[i] == board[j] + offset:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
        if min_attact == []:
            return 0
        else:
            h1 = min(min_attact)**2
            return h1
    
    def heuristic_2(self,state):
        """
        H2: Sum across every pair of attacking Queens the weight of the lightest Queen.
        ex: min(3,9)**2 + min(9,1)**2 + min(3,1)**2 + min(4,2)**2 = 3**2 +1**2 +1**2 +2**2  = 15
        input: state
        output: H2 score
        """
        board = np.nonzero(state.T)[1]
        min_attact = []
        for i in range(len(board)):
            for j in range(i+1,len(board)):
                # check same rows attack
                if board[i] == board[j]:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
                # check diagonally attack
                offset = j-i
                if board[i] == board[j] - offset or board[i] == board[j] + offset:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))

        if min_attact == []:
            return 0
        else:
            h2 = sum([i**2 for i in min_attact])        
            return h2
    
    def near_state(self,state):
        """
        input: state
        output: a list of all possible neighbours
        """
        board = np.nonzero(state.T)[1]
        near_states = []

        for col in range(len(board)):
            for row in range(len(board)):
                if row != board[col]:
                    neighbour = copy.deepcopy(state)
                    neighbour[row,col] = state[board[col],col]
                    neighbour[board[col],col] = 0

                    near_states.append(neighbour)
                    
        return near_states
    
    def near_state_position(self,state):
        """
        input: state
        output: a list of all possible neighbours’ position
        """
        board = np.nonzero(state.T)[1]
        near_states_positions = []

        for col in range(len(board)):
            for row in range(len(board)):
                if row != board[col]:
                    neighbour_position = list(board)
                    neighbour_position[col] = row  # Switch column to empty
                    near_states_positions.append(list(neighbour_position))  
                  
        return near_states_positions   
     
    def cost(self,state1,state2):
        """
        input: two states
        output: cost of taking this step
        """
        board1 = np.nonzero(state1.T)[1] 
        board2 = np.nonzero(state2.T)[1]      
        return np.dot(abs(board1-board2),board_value(state1))

In [4]:
class Queen():

    def input_board(self, filename):
        """
        input: filename
        output: a array like matrix
        ex:
        array([[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 2.],
           [0., 0., 0., 4., 0.],
           [0., 3., 0., 0., 0.],
           [9., 0., 1., 0., 0.]])
        """
        state = np.genfromtxt(filename, delimiter=',')
        state[np.isnan(state)] = 0
        return state
    
    def board_value(self,state):
        board = np.nonzero(state.T)[1]
        value = []
        for i in range(len(board)):
            value.append(state[board[i],i]**2)
        return value
    
    
    def heuristic_1(self, state):
        """
        H1: The lightest Queen across all pairs of Queens attacking each other.
        ex: min(3,9, 9,1, 3,1, 4,2) = 1**1
        input: state
        ex: 
        array([[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 2.],
           [0., 0., 0., 4., 0.],
           [0., 3., 0., 0., 0.],
           [9., 0., 1., 0., 0.]])
        output: H1 score
        """
        board = np.nonzero(state.T)[1]
        min_attact = []
        for i in range(len(board)):
            for j in range(i+1,len(board)):
                # check same rows attack
                if board[i] == board[j]:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
                # check diagonally attack
                offset = j-i
                if board[i] == board[j] - offset or board[i] == board[j] + offset:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
        if min_attact == []:
            return 0
        else:
            h1 = min(min_attact)**2
            return h1
    
    def heuristic_2(self,state):
        """
        H2: Sum across every pair of attacking Queens the weight of the lightest Queen.
        ex: min(3,9)**2 + min(9,1)**2 + min(3,1)**2 + min(4,2)**2 = 3**2 +1**2 +1**2 +2**2  = 15
        input: state
        output: H2 score
        """
        board = np.nonzero(state.T)[1]
        min_attact = []
        for i in range(len(board)):
            for j in range(i+1,len(board)):
                # check same rows attack
                if board[i] == board[j]:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))
                # check diagonally attack
                offset = j-i
                if board[i] == board[j] - offset or board[i] == board[j] + offset:
                    min_attact.append(min(state[board[i],i],state[board[j],j]))

        if min_attact == []:
            return 0
        else:
            h2 = sum([i**2 for i in min_attact])        
            return h2
    
    def near_state(self,state):
        """
        input: state
        output: a list of all possible neighbours
        """
        board = np.nonzero(state.T)[1]
        near_states = []

        for col in range(len(board)):
            for row in range(len(board)):
                if row != board[col]:
                    neighbour = copy.deepcopy(state)
                    neighbour[row,col] = state[board[col],col]
                    neighbour[board[col],col] = 0

                    near_states.append(neighbour)
                    
        return near_states
    
    def near_state_position(self,state):
        """
        input: state
        output: a list of all possible neighbours’ position
        """
        board = np.nonzero(state.T)[1]
        near_states_positions = []

        for col in range(len(board)):
            for row in range(len(board)):
                if row != board[col]:
                    neighbour_position = list(board)
                    neighbour_position[col] = row  # Switch column to empty
                    near_states_positions.append(list(neighbour_position))  
                  
        return near_states_positions   
     
    def cost(self,state1,state2):
        """
        input: two states
        output: cost of taking this step
        """
        board1 = np.nonzero(state1.T)[1] 
        board2 = np.nonzero(state2.T)[1]      
        return np.dot(abs(board1-board2),board_value(state1))
        

In [5]:
q = Queen()
state = q.input_board('heavy queens board.csv')
h1 = q.heuristic_1(state)
h2 = q.heuristic_2(state)
neighbour = q.near_state(state)
print(state)
print(h1)
print(h2)
print(neighbour[1])
print(q.board_value(state))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 4. 0.]
 [0. 3. 0. 0. 0.]
 [9. 0. 1. 0. 0.]]
1.0
15.0
[[0. 0. 0. 0. 0.]
 [9. 0. 0. 0. 2.]
 [0. 0. 0. 4. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[81.0, 9.0, 1.0, 16.0, 4.0]


In [16]:
list1 =[[1,2],[3,4]]
list2 = [[5,6],[7,8]]
list1.extend(list2)

In [18]:
a = 5
b = a
b

5

In [19]:
a = 3
b += a
b

8

In [10]:
a = copy.deepcopy(state)
a

array([[10.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 9.,  0.,  1.,  0.,  0.]])

In [11]:
a[0,0] =11
a

array([[11.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 9.,  0.,  1.,  0.,  0.]])

In [12]:
state

array([[10.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 9.,  0.,  1.,  0.,  0.]])

In [108]:
q.cost(state,neighbour[0])

324.0

In [101]:
neighbour[1]

array([[0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 2.],
       [0., 0., 0., 4., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

array([18.,  0.,  0.,  0.,  0.])

In [95]:
print(q.cost(state,neighbour[1]))

7.0


In [94]:
q = Queen()
state = q.input_board('hc_test.csv')
h1 = q.heuristic_1(state)
h2 = q.heuristic_2(state)
print(state)
print(h1)
print(h2)
print(q.board_value(state))

[[0. 0. 1. 0. 0.]
 [9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 0. 4. 0.]
 [0. 0. 0. 0. 2.]]
4.0
13.0
[81.0, 9.0, 1.0, 16.0, 4.0]


In [ ]:
def cost(state1,state2):
    cost_of_columns = sum(abs(state-neighbour[1]))/2
    return sum(cost_of_columns)
    

In [92]:
def board_value(state):
    board = np.nonzero(state.T)[1]
    value = []
    for i in range(len(board)):
        value.append(state[board[i],i]**2)
    return value


In [93]:
board_value(state)

[81.0, 9.0, 1.0, 16.0, 4.0]

In [51]:
board1 = np.nonzero(state.T)[1] 
board2 = np.nonzero(neighbour[1].T)[1]
np.dot(abs(board1-board2),board_value(state))

In [104]:
np.dot(abs(board1-board2),board_value(state))

243.0

In [75]:
board_value(state)

[9.0, 3.0, 1.0, 4.0, 2.0]

In [71]:
abs(state-neighbour[1])

array([[0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 0.]])

In [79]:
value = [9.0, 3.0, 1.0, 4.0, 2.0]

In [81]:
[ x**2 for x in value ]

[81.0, 9.0, 1.0, 16.0, 4.0]

In [57]:
type(board1-board2)
type(board_value(state))

list

In [58]:
np.dot((board1-board2),(board_value(state)))

numpy.float64

In [50]:
print(board1)
print(board2)


[4 3 4 2 1]
[0 4 3 1 2]


In [21]:
x = 'heavy queens board.csv'
def input_board(x):
    file_array = np.genfromtxt(x, delimiter=',')
    file_array[np.isnan(file_array)] = 0
    return file_array
state = input_board(x)
state

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 4., 0.],
       [0., 3., 0., 0., 0.],
       [9., 0., 1., 0., 0.]])

In [28]:
def board_value(state):
    board = np.nonzero(state.T)[1]
    
    value = []
    for i in range(len(board)):
        value.append(state[board[i],i])
    return value
board_value(state)

[9.0, 3.0, 1.0, 4.0, 2.0]

In [117]:
## h1
def h1(board):
    
    min_attact = []
    for i in range(len(board)):
        for j in range(i+1,len(board)):
            # check same rows attack
            if board[i] == board[j]:
                min_attact.append(min(state[board[i],i],state[board[j],j]))
            # check diagonally attack
            offset = j-i
            if board[i] == board[j] - offset or board[i] == board[j] + offset:
                min_attact.append(min(state[board[i],i],state[board[j],j]))
                
    if min_attact == []:
        return 0
    else:
        h = min(min_attact)**2
        return h

In [12]:
## h2
def h2(board):
    
    min_attact = []
    for i in range(len(board)):
        for j in range(i+1,len(board)):
            # check same rows attack
            if board[i] == board[j]:
                min_attact.append(min(state[board[i],i],state[board[j],j]))
            # check diagonally attack
            offset = j-i
            if board[i] == board[j] - offset or board[i] == board[j] + offset:
                min_attact.append(min(state[board[i],i],state[board[j],j]))
    
    if min_attact == []:
        return 0
    else:
        h = sum([i**2 for i in min_attact])
        return h

In [82]:
row_attact=dict()
diagonal_attact_left = dict()
diagonal_attact_right = dict()
for col,row in enumerate([4,3,4,2,1]):
    row_attact.setdefault(row, []).append([row,col])
    diagonal_attact_left.setdefault(col-row, []).append([row,col])
    diagonal_attact_right.setdefault(row+col, []).append([row,col])
print(row_attact)
print(diagonal_attact_left)
print(diagonal_attact_right)

In [142]:
state

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 4., 0.],
       [0., 3., 0., 0., 0.],
       [9., 0., 1., 0., 0.]])

In [143]:
board = np.nonzero(state.T)[1]

In [151]:
near_states = []

# For each state [column] it checks if the neighboring columns are empty
for col in range(len(board)):
    for row in range(len(board)):
        if row != board[col]:
            neighbour = copy.deepcopy(state)
            neighbour[row,col] = state[board[col],col]
            neighbour[board[col],col] = 0
            
            near_states.append(neighbour)
print(near_states[0])
print(len(near_states))

[[9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 4. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
20


In [32]:
def near_state_positions(state):
    """
    input: state
    output: a list of all possible neighbours’ position
    """
    board = np.nonzero(state.T)[1]
    near_states_position = []

    for col in range(len(board)):
        for row in range(len(board)):
            if row != board[col]:
                neighbour_position = list(board)
                neighbour_position[col] = row  # Switch column to empty
                near_states_position.append(list(neighbour_position))   

    return near_states_position  

In [45]:
# a = near_state_positions(state)
# near_state_positions(state)
